INSERT INTO [dbo].[diet] VALUES ('Gluten Free')
,('Ketogenic')
,('Vegetarian')
,('Lacto-Vegetarian')
,('Ovo-Vegetarian')
,('Vegan')
,('Pescetarian')
,('Paleo')
,('Primal')
,('Low FODMAP')
,('Whole30')